### ISSUE TITLE
Provide short description of HPO and MONDO for portal

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#158]
The summary visualizations in the portal reference HPO and MONDO, but users might not know what those are. We need a short description of what HPO/MONDO are, how to use them (can link out to more detailed info), and/or how to interpret the interactive visualization. This blurb was initially suggested to be a tooltip, but we can work with the portal team to figure out the best format. 

Screenshot below - See the Summary tab of the Data Exploration page in the portal for interactivity.

<img width="791" alt="image" src="https://github.com/include-dcc/include-linkml/assets/34149564/7ada5500-2430-46d5-8bf6-54a80221c6f6">

**Comment by twhetzel** [comment]
Here is a proposal:
The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotypic abnormalities encountered in human disease.

MONDO is a disease ontology which provides a unified view of diseases across various life science and clinical disease terminologies.

@monicacecilia any updates you would suggest?

**Comment by lopierra** [comment]
@jthib077 do you have any info about how to use the HPO/MONDO visualizations in the Data Hub? I'm trying to write a short description (based on a request from a recent user interview) but I'm not sure how to describe what the colours represent. 


> The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotypic abnormalities encountered in human disease. MONDO is a disease ontology which provides a unified view of diseases across various life science and clinical disease terminologies. Data on co-occurring conditions is tagged with HPO and/or MONDO terms to provide a standardized vocabulary for searching across cohorts.

**Comment by monicacecilia** [comment]
From 2024-03-12 Data Modeling Call, also add:  

_We annotate the data we receive about participants using ontology terms to facilitate how users explore and unveil insights._

@lopierra 👀 👆🏽

**Comment by jthib077** [comment]
Unfortunately, we don't have a description on hand. I think it may also be important to highlight the arborescence of the tool. Not sure if you all have something that touches on that?

**Comment by lopierra** [comment]
Submitted usersnap requesting the following text be added:

The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotypic abnormalities encountered in human disease.  The INCLUDE DCC annotates data on participants' co-occurring conditions with these ontology terms to provide a standardized vocabulary for searching across cohorts and facilitate data analyses.

MONDO is a disease ontology that provides a unified view of diseases across various life science and clinical disease terminologies. The INCLUDE DCC annotates data on participants' co-occurring conditions with these ontology terms to provide a standardized vocabulary for searching across cohorts and facilitate data analyses.
