### ISSUE TITLE
Develop enumerations for the field: Study Design

### ISSUE THREAD

**Issue by monicacecilia** [include-dcc/include-linkml#179]
Develop enumerations for the field: **Study Design**

To Do: 
1) State requirements
2) Assess portal needs 
3) Update the [spreadsheet](https://docs.google.com/spreadsheets/d/1cHSburUDg6CR4az5FZR82FI992h7cyv-22pLVTFLZvE/edit#gid=693366131) with this information for this field, including enumerated maps
4) Make recommendations for this field

**Comment by lopierra** [comment]
Should we use the standardized list in the dbGaP Study Config template? Not sure which one of these a registry like DS-Connect would be.

- Case Set
- Case-Control
- Clinical Genetic Testing
- Clinical Trial
- Collection
- Control Set
- Cross-Sectional
- Family/Twin/Trios
- Interventional
- Mendelian
- Metagenomics
- Prospective Longitudinal Cohort
- Tumor vs. Matched-Normal
- Xenograft
- Methods

**Comment by lopierra** [comment]
Decided to incorporate the dbGaP fields above.
