### ISSUE TITLE
Improve release notes for RC_v3.0.0

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#184]
Improve auto-generated release notes by highlighting major changes and filtering the granular changes.

https://github.com/include-dcc/include-linkml/releases/tag/v3.0.0_rc1

**Comment by lopierra** [comment]
#118 - ignore
#122 - ignore
#154: Update Assay component to include latest Virtual Biorepository model
#163 and #181:  Update Study component and add new Dataset component to reflect new Study/Dataset pages

**Comment by lopierra** [comment]
#187 Added a new Dataset Manifest component to index files associated with Datasets; refactored LinkML to reuse slots

**Comment by monicacecilia** [comment]
:bowtie: done and done!
