### ISSUE TITLE
Capture feedback from 4th T21RS 

### ISSUE THREAD

**Issue by monicacecilia** [include-dcc/include-linkml#45]
### This super monitors actions on feedback received during the 4th T21RS (Long Beach, CA. 2022)

- Commenters: please provide your feedback in a new comment below. 
- Data Modeling team: 
   - create new item in list below, including title and description 
   - link to ticket(s) in this repo
   - for each entry, toggle tick only _after_ all associated tickets have been closed.

-----------
This list is a work in progress, and it is frequently updated.

- [ ]  Suggestion / Requirement 
   - Description
   - link to ticket(s) 

- [ ]  Suggestion / Requirement 
   - Description
   - link to ticket(s)

**Comment by lopierra** [comment]
- Add longitudinal data for participants - see below for example use cases
  - Use case: look for sudden drop in BMI as marker for AD
  - Use case: look at history of seizures as predictor of cognitive decline
  - Use case: Khor's immune signature in a new cohort (e.g. HTP)
  - Use case: HTP IFN score in a new cohort (e.g. Khor)
  - Use case: effect of starting/stopping a drug (e.g. tofacitinib) on other conditions (e.g. IFN score)

**Comment by lopierra** [comment]
Closing this - @monicacecilia let me know if you have questions about any of the above items.
