### ISSUE TITLE
Add KIN ontology terms to RO

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#56]
We discussed reusing parts of the [KIN ontology](http://purl.org/ga4gh/kin.owl) - at least the labels - to describe family relationships in our model. I think we were also going to add those terms to the [Relations Ontology](https://www.ebi.ac.uk/ols/ontologies/ro) (please correct if that's wrong).

Here are the terms we need based on our current datasets (may need to add more later, but for now the family data we have is relatively simple):
- [isRelativeOf](http://purl.org/ga4gh/kin.owl#KIN_001)
- [isBiologicalRelativeOf](http://purl.org/ga4gh/kin.owl#KIN_002)
- [isBiologicalParentOf](http://purl.org/ga4gh/kin.owl#KIN_003)
- [isBiologicalSiblingOf](http://purl.org/ga4gh/kin.owl#KIN_007)
- [isMultipleBirthSiblingOf](http://purl.org/ga4gh/kin.owl#KIN_009)
- [isBiologicalMotherOf](http://purl.org/ga4gh/kin.owl#KIN_027)
- [isBiologicalFatherOf](http://purl.org/ga4gh/kin.owl#KIN_028)
- [isBiologicalChildOf](http://purl.org/ga4gh/kin.owl#KIN_032)

**Comment by nicolevasilevsky** [comment]
Please let me know when it is confirmed we'd like to add these to RO and I can make tickets on the RO tracker. (There may be a reason why terms like this are not already in RO, I'm not sure if this has ever been requested before).

**Comment by putmantime** [comment]
We think that we do want to use the Kin ontology terms but not add them to RO currently.
