### ISSUE TITLE
Add constraints & make sure they are supported by schematic

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#77]
Validation rules will be important to include after March release.
There is significant logic required by the transformer to implement them.

Add our [standard QA checks](https://docs.google.com/spreadsheets/d/1GMElHlgG5ANNKENs-AF_rtqtDFB1B1JbLqmePMoxfoY/edit#gid=276730587) and possibly [portal-specific checks](https://docs.google.com/spreadsheets/d/1uxFOl-SDpLRPaeIkfpqnksKMyeoK9pNqBDC33OEoBIs/edit#gid=635043356) as constraints

**Comment by lopierra** [comment]
potentially including dynamic enums?

**Comment by milen-sage** [comment]
This is on our radar, but we'd need to align with how LinkML treats that. @putmantime we discussed having a sync up with some of the LinkML team. Not urgent, but it might be an interesting and good collaboration to start planning for.
