### ISSUE TITLE
Proband issues

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#99]
1. What is the definition of _Proband_? Should we use a different term?
2. What should we do about families with 2 affected children (ie. 2 Probands)

I have been using the NCIT definition [here](https://nciterms.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C64435&ns=ncit):

> **Definition:**  The affected family member who seeks medical attention for a genetic disorder thereby bringing the family under study.

**For March** I recommend changing this term to "Anchor" and using this individual as the anchor for family relationships. The Anchor would be the DS participant with the earliest ID in the family, so there will only one Anchor per family. See example [here](https://docs.google.com/spreadsheets/d/1L-sD6CQciIJBeLnq9vO0tUBHKPRKUgEEHyA6CqITfZo/edit#gid=0).

If it is important to be able to have two Probands per family, we can plan for that post-March.

Feedback/suggestions for March, and post-March?

**Comment by RobertJCarroll** [comment]
Thanks Pierrette!

My mental definition is closer to [NHGRI's](https://www.genome.gov/genetics-glossary/Proband)s: 
> A proband is an individual who is affected by a genetic condition or who is concerned they are at risk. Usually, the proband is the first person in a family who brings the concern of a genetic disorder to the attention of healthcare professionals.

I was swayed a little bit the other direction in the conversation. Given that either term would require clarification, I think it's reasonable to continue to use "Proband". I think we should make our operating definition clear in the UI, no matter if we change or not @jthib077 .

Another thing we could potentially expand to later is to include concepts like "Affected sibling" if we find that would add clarity.

**Comment by lopierra** [comment]
Consider adding a Person class that doesn't change across studies. Participant would be about their role in a particular study.

For now, leave as done for Oct 2022 and plan for refactor post March (Matt's PR https://github.com/include-dcc/include-linkml/pull/85)

**Comment by jthib077** [comment]
Hey Robert, would it suffice to add these specifications for the Proband field within the exposed Data dictionary in the Help center? https://help.includedcc.org/docs/harmonized-portal-data 

I think many fields in the portal may need more clarification but from a UI/UX perspective, it might be inconsistent to provide a definition for one field and not for others directly in the UI. It might be better to point users to the data dictionary for this type of clarification.

**Comment by RobertJCarroll** [comment]
That's a reasonable starting point. We can see what users think or if there's confusion and move from there if needed. There are some handy mouseover options in other spaces that might be options.

**Comment by lopierra** [comment]
v4: Dual Probands also causing issues with duplicate families - see [Slack thread](https://teaminclude.slack.com/archives/C068XM9JPC0/p1701449416264419) with @jthib077 :

> We figured that the reason we had duplicate participants is because of portal logic to build the Families based on the relationships we have. This happens mainly because we have a few edge cases where we have 2 probands for one family. The way that we build the family roles is by anchoring on 1 proband and “exploding” the family to say this participant has this relationship with proband of the family.
> Roughly what happens with two probandsi s that we “explode” the family twice since there are 2 probands this participant has this relationship  with proband 2 of the family. In other words, if there are two, it is possible a family member may have a different relationship proband 1 and proband 2 so how do we know how to define the role in the family
> Can you explain what the family relationship model is from your point of view? Just so we have a better understanding of how we can handle this issue. Because naturally, we need to have some sort of anchor to define the family relationships. Are the family relationships always in reference to the proband?
> e.g. below of affected family where 	pt-nj89gesq, and [pt-ant7fm3e](https://portal.includedcc.org/participants/pt-ant7fm3e) , are probands and siblings.  https://portal.includedcc.org/data-exploration/participants?sharedFilterId=ff2935e2-2c6b-46a7-a6ca-3b3e7feab38b

```
  "release_id": "re_20231117_1",
        "sex": "male"
        "family_type": "other",
        "study_id": "HTP",
        "age_at_data_collection": 111,
        "is_proband": true,
        "outcomes": [],
        "nb_biospecimens": 68,
        "down_syndrome_diagnosis": [
            "Down syndrome (MONDO:0008608)"
        ],
        "families_id": "F0084",
        "family": {
            "family_id": "F0084",
            "relations_to_proband": [
                {
                    "role": "sibling",
                    "participant_id": "pt-gyypzmx8zq"
                },
                {
                    "role": "proband",
                    "participant_id": "pt-nj89gesq"
                }
            ]
        },
        "fhir_id": "pt-nj89gesq" 
```

**Comment by lopierra** [comment]
In new Family Model, we will put proband(s)' participant ID into Family along with which disease is under study. Control families won't have any probands. Relationships will be provided separately, not anchored by a proband.
